package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"slices"
	"strings"

	"github.com/jcchavezs/pakay/internal/sources"
	"github.com/jcchavezs/pakay/types"
)

func main() {
	w := &bytes.Buffer{}
	writeValue(w)

	formatted, err := format.Source(w.Bytes())
	if err != nil {
		exitErr(err)
	}

	if err := os.WriteFile("configexport.go", formatted, 0644); err != nil {
		exitErr(err)
	}
}

func exitErr(err error) {
	fmt.Printf("ERROR: %v\n", err)
	os.Exit(1)
}

func writeValue(w *bytes.Buffer) {
	fmt.Fprintln(w, "// Code generated by ./internal/cmd/exportconfig; DO NOT EDIT.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "//go:generate go run ./internal/cmd/exportconfig")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "package pakay")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "import (")

	ss := sources.GetAll()
	slices.SortFunc(ss, func(a, b types.SecretSource) int {
		return strings.Compare(a.ConfigFactory().Type(), b.ConfigFactory().Type())
	})

	for _, s := range ss {
		e := reflect.ValueOf(s.ConfigFactory()).Elem()
		pkg := e.Type().PkgPath()
		fmt.Fprintf(w, "\t%q\n", pkg)
	}
	fmt.Fprintln(w, ")")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "type (")

	for _, s := range ss {
		f := s.ConfigFactory()
		e := reflect.ValueOf(f).Elem()

		var prefix string
		switch f.Type() {
		case "1password":
			prefix = "OnePassword"
		default:
			prefix = f.Type()
		}

		fmt.Fprintf(w, "\t%s%sConfig = %s\n", strings.ToUpper(string(prefix[0])), prefix[1:], e.Type())
	}

	fmt.Fprintln(w, ")")
}
